# Generated by Django 3.0.5 on 2023-10-01 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('venue', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('certificate', models.FileField(blank=True, null=True, upload_to='certificates/')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField()),
                ('status', models.CharField(default='Pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('aadhar_number', models.CharField(max_length=12)),
                ('department', models.CharField(choices=[('Physics', 'Physics'), ('Mathematics', 'Mathemathics'), ('Computer Science', 'Computer Science'), ('Chemistry', 'Chemistry'), ('Economics', 'Economics'), ('History', 'History'), ('Politics', 'Politics'), ('English', 'English'), ('Hindi', 'Hindi'), ('Malayalam', 'Malayalam'), ('Sanskrit', 'Sanskrit'), ('Botany', 'Botany'), ('Statistics', 'Statistics'), ('Zoology', 'Zoology'), ('Commerce', 'Commerce'), ('Physical Education', 'Physical Education')], max_length=30, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True)),
                ('date_of_birth', models.DateField()),
                ('date_of_joining', models.DateField()),
                ('current_address', models.TextField()),
                ('residential_address', models.TextField()),
                ('status', models.CharField(choices=[('working', 'Working'), ('retired', 'Retired'), ('leave', 'On Leave'), ('transfer', 'Transferred')], max_length=10)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cv', models.FileField(blank=True, null=True, upload_to='cv/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
